-- ClasseHub MVP schema + seed data

create table public.classes (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  emoji text default '🏫',
  school_year text default '2025-2026',
  created_at timestamp with time zone default now()
);

create table public.families (
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.classes(id) on delete cascade,
  student_name text not null,
  created_at timestamp with time zone default now()
);

create table public.events (
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.classes(id) on delete cascade,
  title text not null,
  description text,
  details text,
  event_type text not null default 'classe',
  start_date date not null,
  start_time text,
  end_date date,
  location text,
  is_important boolean default false,
  created_at timestamp with time zone default now()
);

create table public.tasks (
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.classes(id) on delete cascade,
  title text not null,
  description text,
  details text,
  due_date date,
  related_event_id bigint references public.events(id) on delete set null,
  is_important boolean default false,
  created_at timestamp with time zone default now()
);

create table public.checklist_items (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete cascade,
  text text not null,
  sort_order integer default 0
);

create table public.polls (
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.classes(id) on delete cascade,
  question text not null,
  description text,
  close_date date,
  is_active boolean default true,
  created_at timestamp with time zone default now()
);

create table public.poll_options (
  id bigint generated by default as identity primary key,
  poll_id bigint not null references public.polls(id) on delete cascade,
  text text not null
);

create table public.poll_votes (
  id bigint generated by default as identity primary key,
  poll_id bigint not null references public.polls(id) on delete cascade,
  option_id bigint not null references public.poll_options(id) on delete cascade,
  family_id bigint not null references public.families(id) on delete cascade,
  created_at timestamp with time zone default now(),
  unique (poll_id, family_id)
);

create table public.organizations (
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.classes(id) on delete cascade,
  title text not null,
  description text,
  date date,
  external_url text,
  is_active boolean default true,
  created_at timestamp with time zone default now()
);

alter table public.classes enable row level security;
alter table public.families enable row level security;
alter table public.events enable row level security;
alter table public.tasks enable row level security;
alter table public.checklist_items enable row level security;
alter table public.polls enable row level security;
alter table public.poll_options enable row level security;
alter table public.poll_votes enable row level security;
alter table public.organizations enable row level security;

create policy "Public read classes" on public.classes for select to anon using (true);
create policy "Public read families" on public.families for select to anon using (true);
create policy "Public read events" on public.events for select to anon using (true);
create policy "Public read tasks" on public.tasks for select to anon using (true);
create policy "Public read checklist" on public.checklist_items for select to anon using (true);
create policy "Public read polls" on public.polls for select to anon using (true);
create policy "Public read poll options" on public.poll_options for select to anon using (true);
create policy "Public read poll votes" on public.poll_votes for select to anon using (true);
create policy "Public insert poll votes" on public.poll_votes for insert to anon with check (true);
create policy "Public update poll votes" on public.poll_votes for update to anon using (true) with check (true);
create policy "Public read organizations" on public.organizations for select to anon using (true);

insert into public.classes (slug, name, emoji, school_year) values
('orenetes', 'Orenetes', '🐦', '2025-2026'),
('senglars', 'Senglars', '🐗', '2025-2026');

insert into public.families (class_id, student_name)
select c.id, x.name from public.classes c cross join (values
('Èric Badia'),('Àlex Barràs'),('Ramón Carbonell'),('Arlet Fernández'),('Guim Garrido'),('Arnau Griñó'),('Jana Jiménez'),('Aina Mariscal'),('Hugo Luis Martínez'),('Oriol Ollé'),('Sara Oosterhoff'),('Arlet Pagès'),('Oliver Porqueras'),('Nil Sala'),('Mia Sardañés'),('Nil Segura'),('Greta Surís'),('Kira Tujunen'),('Ainara Vela')
) as x(name) where c.slug = 'orenetes';

insert into public.families (class_id, student_name)
select c.id, x.name from public.classes c cross join (values
('Alex (Mitjà)'),('Arnau (Gran)'),('Asier (Gran)'),('Ben (Mitjà)'),('Biel (Gran)'),('Biel (Menut)'),('Bruno (Mitjà)'),('Claudia (Gran)'),('Clementina (Mitjana)'),('Didac (Gran)'),('Jorge (Gran)'),('Lars (Mitjà)'),('Laura (Mitjana)'),('Maia (Menuda)'),('Martin (Mitjà)'),('Ona (Menuda)'),('Otto (Menut)'),('Paula (Gran)'),('Peyton-Nicole (Menuda)'),('Pol (Mitjà)')
) as x(name) where c.slug = 'senglars';

insert into public.events (class_id, title, description, details, event_type, start_date, start_time, location, is_important)
select id, 'Excursió a la platja del Prat', 'Sortida a la platja per jugar amb la sorra, agafar petxines i refrescar-se.', 'Aquest dia no cal portar la fruita. Tornaran a dinar a l’escola. Cal venir amb crema solar posada i gorra. Es demana molta puntualitat.', 'escola', '2026-06-03', null, 'Platja del Prat', true from public.classes where slug in ('orenetes','senglars');

insert into public.events (class_id, title, description, details, event_type, start_date, start_time, location, is_important)
select id, 'Festa d’estiu', 'Festa de final de curs de l’escola.', 'Trobada festiva de l’escola amb activitats i ambient de final de curs. Ideal per a famílies noves que encara no coneixen la dinàmica.', 'escola', '2026-06-06', null, 'Escola Costa i Llobera', false from public.classes where slug in ('orenetes','senglars');

insert into public.events (class_id, title, description, details, event_type, start_date, start_time, location, is_important)
select id, 'Sopar d’estiu de famílies', 'Sopar de famílies de la classe.', 'Trobada informal de famílies per compartir el final de curs.', 'classe', '2026-06-11', '20:00', 'Escola Costa i Llobera', true from public.classes where slug in ('orenetes','senglars');

insert into public.events (class_id, title, description, details, event_type, start_date, start_time, location, is_important)
select id, 'Celebració d’aniversaris del 3r trimestre', 'Celebració conjunta dels aniversaris de la classe.', 'Activitat de tarda per celebrar els aniversaris del trimestre.', 'classe', '2026-06-12', '17:00', 'Parc de Santa Amèlia', false from public.classes where slug = 'orenetes';

insert into public.events (class_id, title, description, details, event_type, start_date, start_time, location, is_important)
select id, 'Concert infantil', 'Concert infantil a la sala polivalent.', 'Activitat musical de final de curs.', 'escola', '2026-06-17', '09:00', 'Costa i Llobera - Sala Polivalent', false from public.classes where slug in ('orenetes','senglars');

insert into public.checklist_items (event_id, text, sort_order)
select e.id, x.text, x.sort_order
from public.events e
cross join (values
('Banyador posat', 1),('Muda de recanvi', 2),('Tovallola petita', 3),('Cantimplora plena d’aigua', 4),('Pala i galleda amb el nom', 5),('Bossa de plàstic per la roba mullada', 6),('Gorra', 7),('Crema solar posada des de casa', 8)
) as x(text, sort_order)
where e.title = 'Excursió a la platja del Prat';

insert into public.tasks (class_id, title, description, details, due_date, is_important)
select id, 'Portar plantes aromàtiques i flors de camp', 'Les Orenetes poden portar plantes aromàtiques i flors de camp la setmana vinent.', 'Aprofitant aquests dies de festa i bon temps, les mestres han demanat portar plantes aromàtiques i flors de camp a l’escola.', '2026-06-08', true from public.classes where slug = 'orenetes';

insert into public.polls (class_id, question, description, close_date, is_active)
select id, 'Comiat dels Grans', 'Votació per decidir l’opció preferida de participació al comiat.', '2026-06-07', true from public.classes where slug = 'orenetes';

insert into public.poll_options (poll_id, text)
select p.id, x.text from public.polls p cross join (values ('Opció A'),('Opció B'),('Opció C')) as x(text) where p.question = 'Comiat dels Grans';

insert into public.organizations (class_id, title, description, date, external_url, is_active)
select id, 'Sopar de final de curs', 'Apunta què portareu i consulta les aportacions de la classe.', '2026-06-11', case when slug='orenetes' then 'https://sopar-orenetes.vercel.app/' else 'https://sopar-senglars.vercel.app/' end, true from public.classes where slug in ('orenetes','senglars');
