create table if not exists public.ch_checklist_item_status (
  id bigint generated by default as identity primary key,
  checklist_item_id bigint not null references public.ch_checklist_items(id) on delete cascade,
  family_id bigint not null references public.ch_families(id) on delete cascade,
  is_done boolean not null default true,
  updated_at timestamp with time zone not null default now(),
  unique (checklist_item_id, family_id)
);

alter table public.ch_checklist_item_status enable row level security;

create or replace function public.set_checklist_item_status_with_pin(
  p_class_id bigint,
  p_access_pin text,
  p_checklist_item_id bigint,
  p_is_done boolean
)
returns table(
  checklist_item_id bigint,
  family_id bigint,
  is_done boolean
)
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_family_id bigint;
  v_item_exists boolean;
begin
  select f.id
  into v_family_id
  from public.ch_families f
  where f.class_id = p_class_id
    and f.is_active is not false
    and trim(f.access_pin) = trim(p_access_pin)
  limit 1;

  if v_family_id is null then
    raise exception 'Invalid family PIN';
  end if;

  select exists (
    select 1
    from public.ch_checklist_items ci
    join public.ch_events e on e.id = ci.event_id
    where ci.id = p_checklist_item_id
      and (
        e.class_id = p_class_id
        or (
          e.event_type = 'escola'
          and e.class_id is null
        )
      )
  )
  into v_item_exists;

  if not v_item_exists then
    raise exception 'Invalid checklist item';
  end if;

  if p_is_done then
    insert into public.ch_checklist_item_status as status (
      checklist_item_id,
      family_id,
      is_done,
      updated_at
    )
    values (
      p_checklist_item_id,
      v_family_id,
      true,
      now()
    )
    on conflict on constraint ch_checklist_item_status_checklist_item_id_family_id_key
    do update set
      is_done = true,
      updated_at = now();
  else
    delete from public.ch_checklist_item_status status
    where status.checklist_item_id = p_checklist_item_id
      and status.family_id = v_family_id;
  end if;

  return query
  select
    p_checklist_item_id as checklist_item_id,
    v_family_id as family_id,
    p_is_done as is_done;
end;
$function$;

grant execute on function public.set_checklist_item_status_with_pin(
  bigint,
  text,
  bigint,
  boolean
) to anon;

grant execute on function public.set_checklist_item_status_with_pin(
  bigint,
  text,
  bigint,
  boolean
) to authenticated;

create or replace function public.get_checklist_item_status_with_pin(
  p_class_id bigint,
  p_access_pin text
)
returns table(
  checklist_item_id bigint,
  family_id bigint,
  is_done boolean
)
language sql
security definer
set search_path to 'public'
as $function$
  select
    s.checklist_item_id,
    s.family_id,
    s.is_done
  from public.ch_checklist_item_status s
  join public.ch_families f on f.id = s.family_id
  where f.class_id = p_class_id
    and f.is_active is not false
    and trim(f.access_pin) = trim(p_access_pin)
    and s.is_done = true;
$function$;

grant execute on function public.get_checklist_item_status_with_pin(
  bigint,
  text
) to anon;

grant execute on function public.get_checklist_item_status_with_pin(
  bigint,
  text
) to authenticated;
